-- MySQL Script generated by MySQL Workbench
-- Mon Nov  7 11:04:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema E-Commerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema E-Commerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `E-Commerce` DEFAULT CHARACTER SET utf8 ;
USE `E-Commerce` ;

-- -----------------------------------------------------
-- Table `E-Commerce`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E-Commerce`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(65) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `Tempo_Carencia` INT NOT NULL DEFAULT 30,
  `Data_Nascimento` DATE NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E-Commerce`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E-Commerce`.`Endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `CEP` VARCHAR(45) NOT NULL,
  `Numero` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idEndereco`, `Cliente_idCliente`),
  INDEX `fk_Endereco_Cliente_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `E-Commerce`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E-Commerce`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E-Commerce`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `Status` ENUM('Em andamento', 'Processando', 'Enviado', 'Entregue') GENERATED ALWAYS AS ('Processando') VIRTUAL,
  `Data_Emissao` DATE NOT NULL,
  `Data_Prevista` DATE NOT NULL,
  `Endereco_idEndereco` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `Endereco_idEndereco`, `Cliente_idCliente`),
  INDEX `fk_Pedido_Endereco1_idx` (`Endereco_idEndereco` ASC) VISIBLE,
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `E-Commerce`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `E-Commerce`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E-Commerce`.`Vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E-Commerce`.`Vendedor` (
  `Cliente_idCliente` INT NOT NULL,
  `Razão Social` VARCHAR(45) NULL,
  `Avaliacao` INT NULL,
  PRIMARY KEY (`Cliente_idCliente`),
  CONSTRAINT `fk_Vendedor_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `E-Commerce`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E-Commerce`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E-Commerce`.`Fornecedor` (
  `idFornecedor` INT NOT NULL,
  `Razao_Social` VARCHAR(60) NOT NULL,
  `CNPJ` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFornecedor`),
  UNIQUE INDEX `Razao_Social_UNIQUE` (`Razao_Social` ASC) VISIBLE,
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E-Commerce`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E-Commerce`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `Fornecedor_idFornecedor` INT NULL,
  `Vendedor_Cliente_idCliente` INT NULL,
  `Nome` VARCHAR(60) NOT NULL,
  `Categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProduto`),
  INDEX `fk_Produto_Fornecedor1_idx` (`Fornecedor_idFornecedor` ASC) VISIBLE,
  INDEX `fk_Produto_Vendedor1_idx` (`Vendedor_Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_Fornecedor1`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `E-Commerce`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_Vendedor1`
    FOREIGN KEY (`Vendedor_Cliente_idCliente`)
    REFERENCES `E-Commerce`.`Vendedor` (`Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E-Commerce`.`Produto_Por_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E-Commerce`.`Produto_Por_Pedido` (
  `Produto_idProduto` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Quantidade` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`Produto_idProduto`, `Pedido_idPedido`),
  INDEX `fk_Produto_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  INDEX `fk_Produto_has_Pedido_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Pedido_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `E-Commerce`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `E-Commerce`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E-Commerce`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E-Commerce`.`Estoque` (
  `idEstoque` INT NOT NULL,
  `Produto_idProduto` INT NULL,
  `Quantidade` INT NULL DEFAULT 1,
  UNIQUE INDEX `Produto_idProduto_UNIQUE` (`Produto_idProduto` ASC) VISIBLE,
  PRIMARY KEY (`idEstoque`),
  CONSTRAINT `fk_Estoque_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `E-Commerce`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E-Commerce`.`Estoque_Produto_Por_Vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E-Commerce`.`Estoque_Produto_Por_Vendedor` (
  `Vendedor_Cliente_idCliente` INT NOT NULL,
  `Estoque_Produto_idProduto` INT NOT NULL,
  PRIMARY KEY (`Vendedor_Cliente_idCliente`, `Estoque_Produto_idProduto`),
  INDEX `fk_Vendedor_has_Estoque_Estoque1_idx` (`Estoque_Produto_idProduto` ASC) VISIBLE,
  INDEX `fk_Vendedor_has_Estoque_Vendedor1_idx` (`Vendedor_Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Vendedor_has_Estoque_Vendedor1`
    FOREIGN KEY (`Vendedor_Cliente_idCliente`)
    REFERENCES `E-Commerce`.`Vendedor` (`Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendedor_has_Estoque_Estoque1`
    FOREIGN KEY (`Estoque_Produto_idProduto`)
    REFERENCES `E-Commerce`.`Estoque` (`Produto_idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
